/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dndpt;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;

/**
 *
 * @author Justin
 */
public class Create_Char extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    boolean playerAdmin = false;
    int pid;
    ResultSet rs;
    /**
     * Creates new form NewJFrame
     */
    public Create_Char(int pid, Connection conn) {
        initComponents();
        this.conn = conn;
        this.pid = pid;
        wep1.setVisible(false);
        wep2.setVisible(false);
        wep3.setVisible(false);
        String sql = "SELECT name FROM spell";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                String name = rs.getString("name");
                spell1.addItem(name); spell2.addItem(name);
                spell3.addItem(name); spell4.addItem(name);
            }
        } catch(Exception e) {}
        finally {
            try {
                rs.close();
                pst.close();
            }catch (Exception e){}
        }
        System.out.println(ani.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cname = new javax.swing.JTextField();
        clevel = new javax.swing.JTextField();
        cclass = new javax.swing.JComboBox<>();
        cbg = new javax.swing.JComboBox<>();
        pname = new javax.swing.JLabel();
        crace = new javax.swing.JComboBox<>();
        alignment = new javax.swing.JComboBox<>();
        group = new javax.swing.JTextField();
        st_str = new javax.swing.JCheckBox();
        st_dex = new javax.swing.JCheckBox();
        st_con = new javax.swing.JCheckBox();
        st_int = new javax.swing.JCheckBox();
        st_wis = new javax.swing.JCheckBox();
        st_cha = new javax.swing.JCheckBox();
        acr = new javax.swing.JCheckBox();
        ani = new javax.swing.JCheckBox();
        arc = new javax.swing.JCheckBox();
        ath = new javax.swing.JCheckBox();
        dec = new javax.swing.JCheckBox();
        his = new javax.swing.JCheckBox();
        ins = new javax.swing.JCheckBox();
        inti = new javax.swing.JCheckBox();
        inv = new javax.swing.JCheckBox();
        med = new javax.swing.JCheckBox();
        nat = new javax.swing.JCheckBox();
        perc = new javax.swing.JCheckBox();
        perf = new javax.swing.JCheckBox();
        pers = new javax.swing.JCheckBox();
        rel = new javax.swing.JCheckBox();
        sle = new javax.swing.JCheckBox();
        ste = new javax.swing.JCheckBox();
        sur = new javax.swing.JCheckBox();
        cstr = new javax.swing.JTextField();
        ccha = new javax.swing.JTextField();
        cdex = new javax.swing.JTextField();
        ccon = new javax.swing.JTextField();
        cint = new javax.swing.JTextField();
        cwis = new javax.swing.JTextField();
        lang1 = new javax.swing.JTextField();
        lang2 = new javax.swing.JTextField();
        lang3 = new javax.swing.JTextField();
        inspiration = new javax.swing.JTextField();
        initiative = new javax.swing.JTextField();
        speed = new javax.swing.JTextField();
        vision = new javax.swing.JTextField();
        pass_perc = new javax.swing.JTextField();
        scrollyP = new javax.swing.JScrollPane();
        traits = new javax.swing.JTextArea();
        att_type = new javax.swing.JComboBox<>();
        g = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        s = new javax.swing.JTextField();
        ccha4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        hp = new javax.swing.JTextField();
        hitDie = new javax.swing.JTextField();
        spell4 = new javax.swing.JComboBox<>();
        spell1 = new javax.swing.JComboBox<>();
        spell2 = new javax.swing.JComboBox<>();
        spell3 = new javax.swing.JComboBox<>();
        wep3 = new javax.swing.JComboBox<>();
        wep1 = new javax.swing.JComboBox<>();
        wep2 = new javax.swing.JComboBox<>();
        bg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(765, 1040));
        setSize(new java.awt.Dimension(1003, 784));
        getContentPane().setLayout(null);

        cname.setText("name");
        cname.setAutoscrolls(false);
        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        getContentPane().add(cname);
        cname.setBounds(80, 70, 150, 20);

        clevel.setText("#");
        getContentPane().add(clevel);
        clevel.setBounds(270, 70, 30, 20);

        cclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barbarian", "Bard", "Cleric", "Druid", "Fighter", "Monk", "Paladin", "Ranger", "Sorcerer", "Wizard" }));
        getContentPane().add(cclass);
        cclass.setBounds(320, 50, 71, 20);

        cbg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acolyte", "Charlatan", "Criminal", "Entertainer", "Folk Hero", "Guild Artisan", "Hermit", "Noble", "Outlander", "Sage", "Sailor", "Soldier", "Urchin" }));
        getContentPane().add(cbg);
        cbg.setBounds(510, 50, 100, 20);

        pname.setText("YOU");
        getContentPane().add(pname);
        pname.setBounds(630, 44, 50, 30);

        crace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dragonborn", "Dwarf", "Eladrin", "Elf", "Gnome", "Half-elf", "Half-orc", "Halfling", "Human", "Tiefling" }));
        getContentPane().add(crace);
        crace.setBounds(420, 50, 90, 20);

        alignment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lawful Good", "Neutral Good", "Chaotic Good", "Lawful Neutral", "Neutral", "Chaotic Neutral", "Lawful Evil", "Neutral Evil", "Chaotic Evil" }));
        getContentPane().add(alignment);
        alignment.setBounds(460, 80, 120, 20);

        group.setText("null;");
        getContentPane().add(group);
        group.setBounds(590, 80, 110, 20);

        st_str.setName("Strength"); // NOI18N
        st_str.setOpaque(false);
        getContentPane().add(st_str);
        st_str.setBounds(120, 230, 20, 21);

        st_dex.setName("Dexterity"); // NOI18N
        st_dex.setOpaque(false);
        getContentPane().add(st_dex);
        st_dex.setBounds(120, 240, 20, 30);

        st_con.setName("Constitution"); // NOI18N
        st_con.setOpaque(false);
        getContentPane().add(st_con);
        st_con.setBounds(120, 260, 20, 20);

        st_int.setName("Intelligence"); // NOI18N
        st_int.setOpaque(false);
        getContentPane().add(st_int);
        st_int.setBounds(120, 280, 20, 21);

        st_wis.setName("Wisdom"); // NOI18N
        st_wis.setOpaque(false);
        getContentPane().add(st_wis);
        st_wis.setBounds(120, 290, 20, 30);

        st_cha.setName("Charisma"); // NOI18N
        st_cha.setOpaque(false);
        getContentPane().add(st_cha);
        st_cha.setBounds(120, 310, 20, 21);

        acr.setName("Acrobatics"); // NOI18N
        acr.setOpaque(false);
        getContentPane().add(acr);
        acr.setBounds(120, 361, 20, 30);

        ani.setName("Animal Handling"); // NOI18N
        ani.setOpaque(false);
        getContentPane().add(ani);
        ani.setBounds(120, 380, 20, 20);

        arc.setName("Arcana"); // NOI18N
        arc.setOpaque(false);
        getContentPane().add(arc);
        arc.setBounds(120, 400, 20, 21);

        ath.setName("Athletics"); // NOI18N
        ath.setOpaque(false);
        getContentPane().add(ath);
        ath.setBounds(120, 411, 20, 30);

        dec.setName("Deception"); // NOI18N
        dec.setOpaque(false);
        getContentPane().add(dec);
        dec.setBounds(120, 430, 20, 30);

        his.setName("History"); // NOI18N
        his.setOpaque(false);
        getContentPane().add(his);
        his.setBounds(120, 450, 20, 21);

        ins.setName("Insight"); // NOI18N
        ins.setOpaque(false);
        getContentPane().add(ins);
        ins.setBounds(120, 461, 20, 30);

        inti.setName("Intimidation"); // NOI18N
        inti.setOpaque(false);
        getContentPane().add(inti);
        inti.setBounds(120, 480, 20, 21);

        inv.setName("Investigation"); // NOI18N
        inv.setOpaque(false);
        getContentPane().add(inv);
        inv.setBounds(120, 491, 20, 30);

        med.setName("Medicine"); // NOI18N
        med.setOpaque(false);
        getContentPane().add(med);
        med.setBounds(120, 501, 20, 40);

        nat.setName("Nature"); // NOI18N
        nat.setOpaque(false);
        getContentPane().add(nat);
        nat.setBounds(120, 530, 20, 21);

        perc.setName("Perception"); // NOI18N
        perc.setOpaque(false);
        getContentPane().add(perc);
        perc.setBounds(120, 541, 20, 30);

        perf.setName("Performance"); // NOI18N
        perf.setOpaque(false);
        getContentPane().add(perf);
        perf.setBounds(120, 561, 20, 30);

        pers.setName("Persuasion"); // NOI18N
        pers.setOpaque(false);
        getContentPane().add(pers);
        pers.setBounds(120, 571, 20, 40);

        rel.setName("Religion"); // NOI18N
        rel.setOpaque(false);
        getContentPane().add(rel);
        rel.setBounds(120, 600, 20, 21);

        sle.setName("Sleight of Hand"); // NOI18N
        sle.setOpaque(false);
        getContentPane().add(sle);
        sle.setBounds(120, 611, 20, 30);

        ste.setName("Stealth"); // NOI18N
        ste.setOpaque(false);
        getContentPane().add(ste);
        ste.setBounds(120, 630, 20, 21);

        sur.setName("Survival"); // NOI18N
        sur.setOpaque(false);
        getContentPane().add(sur);
        sur.setBounds(120, 641, 20, 30);

        cstr.setForeground(new java.awt.Color(102, 102, 102));
        cstr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cstr.setText("15");
        getContentPane().add(cstr);
        cstr.setBounds(50, 210, 40, 40);

        ccha.setForeground(new java.awt.Color(102, 102, 102));
        ccha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccha.setText("8");
        getContentPane().add(ccha);
        ccha.setBounds(50, 680, 40, 30);

        cdex.setForeground(new java.awt.Color(102, 102, 102));
        cdex.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cdex.setText("14");
        getContentPane().add(cdex);
        cdex.setBounds(50, 310, 40, 30);

        ccon.setForeground(new java.awt.Color(102, 102, 102));
        ccon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccon.setText("13");
        getContentPane().add(ccon);
        ccon.setBounds(50, 400, 40, 30);

        cint.setForeground(new java.awt.Color(102, 102, 102));
        cint.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cint.setText("12");
        getContentPane().add(cint);
        cint.setBounds(50, 490, 40, 30);

        cwis.setForeground(new java.awt.Color(102, 102, 102));
        cwis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cwis.setText("10");
        getContentPane().add(cwis);
        cwis.setBounds(50, 590, 40, 30);

        lang1.setText("language");
        getContentPane().add(lang1);
        lang1.setBounds(50, 740, 100, 20);

        lang2.setText("language");
        getContentPane().add(lang2);
        lang2.setBounds(50, 760, 100, 20);

        lang3.setText("language");
        getContentPane().add(lang3);
        lang3.setBounds(50, 780, 100, 20);

        inspiration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inspiration.setText("0");
        getContentPane().add(inspiration);
        inspiration.setBounds(120, 150, 30, 20);

        initiative.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        initiative.setText("0");
        getContentPane().add(initiative);
        initiative.setBounds(652, 170, 50, 20);

        speed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        speed.setText("25");
        getContentPane().add(speed);
        speed.setBounds(660, 220, 30, 30);

        vision.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vision.setText("25");
        getContentPane().add(vision);
        vision.setBounds(660, 270, 30, 30);

        pass_perc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass_perc.setText("0");
        getContentPane().add(pass_perc);
        pass_perc.setBounds(119, 700, 40, 20);

        traits.setColumns(20);
        traits.setRows(5);
        scrollyP.setViewportView(traits);

        getContentPane().add(scrollyP);
        scrollyP.setBounds(280, 550, 450, 160);

        att_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Magical", "Non-Magical" }));
        att_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                att_typeActionPerformed(evt);
            }
        });
        getContentPane().add(att_type);
        att_type.setBounds(290, 500, 130, 20);

        g.setForeground(new java.awt.Color(102, 102, 102));
        g.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        g.setText("0");
        getContentPane().add(g);
        g.setBounds(290, 880, 40, 30);

        c.setForeground(new java.awt.Color(102, 102, 102));
        c.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c.setText("0");
        getContentPane().add(c);
        c.setBounds(290, 790, 40, 30);

        s.setForeground(new java.awt.Color(102, 102, 102));
        s.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s.setText("0");
        getContentPane().add(s);
        s.setBounds(290, 820, 40, 30);

        ccha4.setForeground(new java.awt.Color(102, 102, 102));
        ccha4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccha4.setText("0");
        getContentPane().add(ccha4);
        ccha4.setBounds(290, 850, 40, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(650, 0, 110, 30);

        hp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hp.setText("0");
        getContentPane().add(hp);
        hp.setBounds(340, 260, 90, 20);

        hitDie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hitDie.setText("1d12");
        hitDie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitDieActionPerformed(evt);
            }
        });
        getContentPane().add(hitDie);
        hitDie.setBounds(520, 160, 90, 80);

        getContentPane().add(spell4);
        spell4.setBounds(290, 440, 200, 20);

        getContentPane().add(spell1);
        spell1.setBounds(290, 350, 200, 20);

        getContentPane().add(spell2);
        spell2.setBounds(290, 380, 200, 20);

        getContentPane().add(spell3);
        spell3.setBounds(290, 410, 200, 20);

        getContentPane().add(wep3);
        wep3.setBounds(290, 410, 200, 20);

        getContentPane().add(wep1);
        wep1.setBounds(290, 350, 200, 20);

        wep2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(wep2);
        wep2.setBounds(290, 380, 200, 20);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/dndcharsheet copy.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 765, 990);

        jMenu1.setText("File");

        jMenuItem1.setText("Cancel");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * insert char statement
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql = "INSERT INTO character VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,";
        String sql2 = " ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,";
        String sql3 =  "?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            //set 17, 18, 19 to st check boxes
            //set 20-24 sk check boxes
            pst = conn.prepareStatement(sql + sql2 + sql3);
            pst.setString(1, Integer.toString(pid)); pst.setString(2, cname.getText()); pst.setString(3, clevel.getText());
            pst.setString(4, cclass.getSelectedItem().toString()); pst.setString(5, cbg.getSelectedItem().toString());
            pst.setString(6, crace.getSelectedItem().toString()); pst.setString(7, alignment.getSelectedItem().toString());
            pst.setString(8, "0"); pst.setString(9, cstr.getText());  pst.setString(10, cdex.getText()); pst.setString(11, ccon.getText());
            pst.setString(12, cint.getText()); pst.setString(13, cwis.getText()); pst.setString(14, ccha.getText()); pst.setString(15, inspiration.getText());
            pst.setString(16, "0"); pst.setString(25, pass_perc.getText());  pst.setString(26, lang1.getText()); pst.setString(27, lang2.getText());
            pst.setString(28, lang3.getText());  pst.setString(29, "10");  pst.setString(30, initiative.getText()); pst.setString(31, speed.getText());
            pst.setString(32, hp.getText()); pst.setString(33, hp.getText()); pst.setString(34, hitDie.getText()); pst.setString(35, "0"); pst.setString(36, "0");
            pst.setString(40, g.getText()); pst.setString(41, s.getText()); pst.setString(42, c.getText()); 
            for (int i = 43; i < 52; i++){
                pst.setString(i, "0");
            }
            for (int i = 56; i < 62; i++){
                pst.setString(i, "0");
            }
            pst.setString(52, traits.getText());
            
            JCheckBox[] st = new JCheckBox[6];
            st[0] = st_cha; st[1] = st_con; st[2] = st_dex; st[3] = st_int; st[4] = st_str; st[5] = st_wis;
            JCheckBox[] sk = new JCheckBox[18];
            sk[0] = acr; sk[1] = ani; sk[2] = arc; sk[3] = ath; sk[4] = dec; sk[5] = his; sk[6] = ins; sk[7] = perc; sk[8] = inv;
            sk[9] = med; sk[10] = nat; sk[11] = perf; sk[12] = pers; sk[13] = rel; sk[14] = sle; sk[15] = ste; sk[16] = sur; sk[17] = inti;
            int count = 0;
            for (int i = 0; i < st.length-1; i++){
                System.out.println(st[i].getName());
                if (st[i].isSelected()){
                    pst.setString(count+17, st[i].getName());
                    count++;
                }
                if ((count + 1) > 3)
                    break;
            }
            count = 0;
            for (int i = 0; i < sk.length-1; i++){
                if (sk[i].isSelected()){
                    pst.setString(count+20, sk[i].getName());
                    count++;
                }
                if ((count + 1) > 5)
                    break;
            }
            String selection = att_type.getSelectedItem().toString();
            if (selection.equals("Magical")) {
                pst.setString(37, "0"); pst.setString(38, "0"); pst.setString(39, "0");
                //53-61
                pst.setString(53, getID("spell", spell1.getSelectedItem().toString())); 
                pst.setString(54, getID("spell", spell2.getSelectedItem().toString())); 
                pst.setString(55, getID("spell", spell3.getSelectedItem().toString()));
                pst.setString(56, getID("spell", spell4.getSelectedItem().toString()));
                for (int i = 37; i < 40; i++){
                    pst.setString(i, "0");
                }
            } else {
                for(int i = 54; i < 58; i++){
                    pst.setString(i, "0");
                }
                
                pst.setString(37, getID("equipment", wep1.getSelectedItem().toString()));
                pst.setString(38, getID("equipment", wep2.getSelectedItem().toString()));
                pst.setString(39, getID("equipment", wep3.getSelectedItem().toString()));
            }
            pst.executeUpdate();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        this.setVisible(false);
        this.dispose();
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hitDieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitDieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hitDieActionPerformed

    /**
     * gets ID of a selected item given name, table
     * @param table table to query from
     * @param name name to search for
     * @return 
     */
    public String getID(String table, String name) {
        String sql = "SELECT id, name FROM " + table + " WHERE name = ?";
        int result = 0;
        PreparedStatement tpst = null;
        ResultSet trs = null;
        try {
            
            tpst = conn.prepareStatement(sql);
            tpst.setString(1, name);
            trs = tpst.executeQuery();
            result = trs.getInt("id");
        }catch(Exception e) {}
        finally {
            try{
                trs.close();
                tpst.close();
            } catch (Exception e) {}
        }
        return Integer.toString(result);
    }
    
    /**
     * shows input types based on attack type
     * @param evt 
     */
    private void att_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_att_typeActionPerformed
        String selection = att_type.getSelectedItem().toString();
        if (selection.equals("Magical")){
            spell1.setVisible(true);
            spell2.setVisible(true);
            spell3.setVisible(true);
            spell4.setVisible(true);
            wep1.setVisible(false);
            wep2.setVisible(false);
            wep3.setVisible(false);
            String sql = "SELECT name FROM spell";
            try {
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                while(rs.next()){
                    String name = rs.getString("name");
                    spell1.addItem(name); spell2.addItem(name);
                    spell3.addItem(name); spell4.addItem(name);
                }
            } catch(Exception e) {}
            finally {
                try {
                    rs.close();
                    pst.close();
                }catch (Exception e){}
            }
        } else {
            spell1.setVisible(false);
            spell2.setVisible(false);
            spell3.setVisible(false);
            spell4.setVisible(false);
            wep1.setVisible(true);
            wep2.setVisible(true);
            wep3.setVisible(true);
            String sql = "SELECT name FROM equipment WHERE family = ?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, "Weapons");
                rs = pst.executeQuery();
                while(rs.next()){
                    String name = rs.getString("name");
                    wep1.addItem(name); wep2.addItem(name);
                    wep3.addItem(name);
                }
            } catch(Exception e) {}
            finally {
                try {
                    rs.close();
                    pst.close();
                }catch (Exception e){}
            }
        } 
    }//GEN-LAST:event_att_typeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox acr;
    private javax.swing.JComboBox<String> alignment;
    private javax.swing.JCheckBox ani;
    private javax.swing.JCheckBox arc;
    private javax.swing.JCheckBox ath;
    private javax.swing.JComboBox<String> att_type;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField c;
    private javax.swing.JComboBox<String> cbg;
    private javax.swing.JTextField ccha;
    private javax.swing.JTextField ccha4;
    private javax.swing.JComboBox<String> cclass;
    private javax.swing.JTextField ccon;
    private javax.swing.JTextField cdex;
    private javax.swing.JTextField cint;
    private javax.swing.JTextField clevel;
    private javax.swing.JTextField cname;
    private javax.swing.JComboBox<String> crace;
    private javax.swing.JTextField cstr;
    private javax.swing.JTextField cwis;
    private javax.swing.JCheckBox dec;
    private javax.swing.JTextField g;
    private javax.swing.JTextField group;
    private javax.swing.JCheckBox his;
    private javax.swing.JTextField hitDie;
    private javax.swing.JTextField hp;
    private javax.swing.JTextField initiative;
    private javax.swing.JCheckBox ins;
    private javax.swing.JTextField inspiration;
    private javax.swing.JCheckBox inti;
    private javax.swing.JCheckBox inv;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField lang1;
    private javax.swing.JTextField lang2;
    private javax.swing.JTextField lang3;
    private javax.swing.JCheckBox med;
    private javax.swing.JCheckBox nat;
    private javax.swing.JTextField pass_perc;
    private javax.swing.JCheckBox perc;
    private javax.swing.JCheckBox perf;
    private javax.swing.JCheckBox pers;
    private javax.swing.JLabel pname;
    private javax.swing.JCheckBox rel;
    private javax.swing.JTextField s;
    private javax.swing.JScrollPane scrollyP;
    private javax.swing.JCheckBox sle;
    private javax.swing.JTextField speed;
    private javax.swing.JComboBox<String> spell1;
    private javax.swing.JComboBox<String> spell2;
    private javax.swing.JComboBox<String> spell3;
    private javax.swing.JComboBox<String> spell4;
    private javax.swing.JCheckBox st_cha;
    private javax.swing.JCheckBox st_con;
    private javax.swing.JCheckBox st_dex;
    private javax.swing.JCheckBox st_int;
    private javax.swing.JCheckBox st_str;
    private javax.swing.JCheckBox st_wis;
    private javax.swing.JCheckBox ste;
    private javax.swing.JCheckBox sur;
    private javax.swing.JTextArea traits;
    private javax.swing.JTextField vision;
    private javax.swing.JComboBox<String> wep1;
    private javax.swing.JComboBox<String> wep2;
    private javax.swing.JComboBox<String> wep3;
    // End of variables declaration//GEN-END:variables
}
